

const sidebars = {

  docs: [
    'index',
    {
      type: 'category',
      label: '入门',
      link: {
        type: 'generated-index' // 添加此参数可以在点击这个 label 的时候有一个概览的界面
      },
      collapsed: false,
      items: [
        'installation',
        'tutorial'
      ]
    },
    {
      type: 'category',
      label: '基础组件',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'elements'
        }
      ]
    },
    {
      type: 'category',
      label: '布局组件',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'layout'
        }
      ]
    },
    'resources',
    {

    }
  ],

  opensourceProject: [
    {
      type: 'autogenerated',
      dirName: 'open-source-project'
    }
  ]

};

module.exports = sidebars;
